# Generated by Django 5.2.1 on 2026-04-21 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='schedule',
            field=models.CharField(blank=True, choices=[('Diurno', 'Diurno'), ('Vespertino', 'Vespertino')], default='Diurno', max_length=20, verbose_name='Jornada'),
        ),
    ]
