# Generated by Django 5.2.1 on 2026-04-16 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicarea',
            options={},
        ),
        migrations.AlterModelOptions(
            name='area',
            options={},
        ),
        migrations.AlterModelOptions(
            name='career',
            options={},
        ),
        migrations.RenameField(
            model_name='academicarea',
            old_name='parent_area',
            new_name='area',
        ),
        migrations.RemoveField(
            model_name='area',
            name='is_academic_direction',
        ),
        migrations.AlterField(
            model_name='academicarea',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='career',
            name='academic_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='careers', to='organization.academicarea'),
        ),
        migrations.AlterField(
            model_name='career',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
