# Generated by Django 5.2.1 on 2025-05-29 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Derivacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.TextField()),
                ('a_area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derivaciones_entrantes', to='core.area')),
                ('atencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='derivaciones', to='core.atencion')),
                ('de_area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derivaciones_salientes', to='core.area')),
                ('usuario_deriva', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derivaciones_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
