# Generated by Django 5.2.1 on 2026-04-21 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casetransfer',
            options={'ordering': ['-created_at']},
        ),
    ]
