# Generated by Django 5.2.1 on 2026-04-16 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('organization', '0002_alter_academicarea_options_alter_area_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='academic_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='organization.academicarea'),
        ),
    ]
