# Generated by Django 5.2.13 on 2026-04-22 20:09

from django.db import migrations, models


def migrate_career_to_careers(apps, schema_editor):
    UserProfile = apps.get_model("accounts", "UserProfile")
    for profile in UserProfile.objects.exclude(career__isnull=True).iterator():
        profile.careers.add(profile.career_id)


def reverse_migrate_careers_to_career(apps, schema_editor):
    UserProfile = apps.get_model("accounts", "UserProfile")
    for profile in UserProfile.objects.all().iterator():
        first_career = profile.careers.order_by("id").first()
        if first_career:
            profile.career_id = first_career.id
            profile.save(update_fields=["career"])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_userprofile_academic_area"),
        ("organization", "0002_alter_academicarea_options_alter_area_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="careers",
            field=models.ManyToManyField(
                blank=True, related_name="profiles", to="organization.career"
            ),
        ),
        migrations.RunPython(
            code=migrate_career_to_careers,
            reverse_code=reverse_migrate_careers_to_career,
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="career",
        ),
    ]
