# Generated by Django 5.2.13 on 2026-04-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_userprofile_career_userprofile_careers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("vrs", "Vicerrector sede (VRS)"),
                    ("dac", "Director académico (DAC)"),
                    ("dc", "Director de carrera (DC)"),
                    ("cc", "Coordinador de carrera (CC)"),
                    ("dae", "Director asuntos estudiantiles (DAE)"),
                    ("scholarship_manager", "Encargado becas"),
                    ("employability_manager", "Encargado empleabilidad"),
                    ("curricular_head", "Jefe curricular"),
                    ("curricular_assistant", "Asistente curricular"),
                    ("local_network_admin", "Administrador de red local"),
                    ("technical_operator", "Operador técnico"),
                    ("subdirector", "Subdirector"),
                    ("tutor", "Tutora"),
                    ("head_tutor", "Jefa tutora"),
                ],
                default="technical_operator",
                max_length=30,
            ),
        ),
    ]
