# Generated by Django 5.2.13 on 2026-04-22 21:41

import django.db.models.deletion
import django.utils.timezone
import psychopedagogy.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0002_alter_student_schedule"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PsychopedagogyRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Activo"),
                            ("on_hold", "En pausa"),
                            ("closed", "Cerrado"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "start_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("end_date", models.DateField(blank=True, null=True)),
                ("support_category", models.CharField(blank=True, max_length=120)),
                (
                    "support_reason",
                    models.TextField(verbose_name="Motivo de acompañamiento"),
                ),
                (
                    "background_notes",
                    models.TextField(
                        blank=True, verbose_name="Antecedentes reportados"
                    ),
                ),
                (
                    "summary",
                    models.TextField(blank=True, verbose_name="Resumen general"),
                ),
                ("observations", models.TextField(blank=True)),
                (
                    "is_confidential",
                    models.BooleanField(
                        default=True, verbose_name="Información confidencial"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="psychopedagogy_records_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "responsible_tutor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="psychopedagogy_records_as_tutor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="psychopedagogy_records",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    (
                        "access_psychopedagogy_module",
                        "Puede acceder al módulo psicopedagógico",
                    ),
                    (
                        "view_all_psychopedagogy_records",
                        "Puede ver todas las fichas psicopedagógicas",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PsychopedagogyLogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entry_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("session", "Sesión"),
                            ("follow_up", "Seguimiento"),
                            ("agreement", "Acuerdo"),
                            ("incident", "Incidencia"),
                            ("other", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("content", models.TextField()),
                (
                    "agreements",
                    models.TextField(blank=True, verbose_name="Acuerdos / acciones"),
                ),
                (
                    "next_follow_up",
                    models.DateField(
                        blank=True, null=True, verbose_name="Próximo seguimiento"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="psychopedagogy_log_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="log_entries",
                        to="psychopedagogy.psychopedagogyrecord",
                    ),
                ),
            ],
            options={
                "ordering": ["-entry_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PsychopedagogyAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attachment_type",
                    models.CharField(
                        choices=[
                            ("report", "Informe"),
                            ("support_plan", "Plan de apoyo"),
                            ("observation", "Observación"),
                            ("other", "Otro"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=psychopedagogy.models.psychopedagogy_attachment_path,
                        validators=[
                            psychopedagogy.models.validate_attachment_extension
                        ],
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Observación del archivo",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="psychopedagogy_attachments_uploaded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="psychopedagogy.psychopedagogyrecord",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="PsychopedagogyRecordAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("can_edit", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "granted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="psychopedagogy_authorizations_granted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authorized_users",
                        to="psychopedagogy.psychopedagogyrecord",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="psychopedagogy_authorizations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("record", "user")},
            },
        ),
    ]
