# Generated by Django 5.2.13 on 2026-04-23 00:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("psychopedagogy", "0001_initial"),
        ("students", "0002_alter_student_schedule"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="psychopedagogyrecord",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("student",),
                name="unique_active_psychopedagogy_record_per_student",
            ),
        ),
    ]
